# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2c1365defffbb01a2ceedb531dcc99ce2895da738a89a72c67cfd1f69e71c826498fa38ce4d7a612d7bfab1c2e65ab8d550ba0f68900d5e210fbd3a2df7bdfd

test:
  secret_key_base: 86d7bd943287aabcb56874499aa08e8ac1fecdcf07d7e06ae71e82c476be9ad76781ae655afde1ad9f427458ff057135e9b4b4600bd13280b8dae4dd2f03ae01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
